export const fareChart = [
    {   
        "id_ride": "1bk",
        "key": "bk1",
        "type":"Bike",
        "fare": 60,
        "passenger":1,
        "image": "https://i.postimg.cc/fWvZdzrP/Frame.png",
    },
    {   
        "id_ride": "2bk",
        "key": "bk1",
        "type":"Bike",
        "fare": 60,
        "passenger": 1,
        "image": "https://i.postimg.cc/fWvZdzrP/Frame.png",
    },
    {   "id_ride": "3bk",
        "key": "bk1",
        "type":"Bike",
        "fare": 60,
        "passenger":1,
        "image": "https://i.postimg.cc/fWvZdzrP/Frame.png",
    },
    {
        "id_ride": "1cr",
        "key": "cr3",
        "type": "Car",
        "fare": 100,
        "passenger":5,
        "image": "https://i.postimg.cc/wTfpWWHc/Frame-2.png",
    },
    {
        "id_ride": "2cr",
        "key": "cr3",
        "type": "Car",
        "fare": 100,
        "passenger": 5,
        "image": "https://i.postimg.cc/wTfpWWHc/Frame-2.png",
    },
    {
        "id_ride": "3cr",
        "key": "cr3",
        "type": "Car",
        "fare": 100,
        "passenger":5 ,
        "image": "https://i.postimg.cc/wTfpWWHc/Frame-2.png",
    },
    {   "id_ride": "1bs",
        "key": "bs2",
        "type": "Bus",
        "fare": 20,
        "passenger":35,
        "image": "https://i.postimg.cc/vHHytRRZ/Frame-1.png",
    },
    {
        "id_ride": "2bs",
        "key": "bs2",
        "type": "Bus",
        "fare": 20 ,
        "passenger": 35,
        "image": "https://i.postimg.cc/vHHytRRZ/Frame-1.png",
    },
    {
        "id_ride": "3bs",
        "key": "bs2",
        "type": "Bus",
        "fare": 20 ,
        "passenger": 35,
        "image": "https://i.postimg.cc/vHHytRRZ/Frame-1.png",
    },
    {
        "id_ride": "1tn",
        "key": "tn4",
        "type":"Train",
        "fare": 15,
        "passenger":70,
        "image": "https://i.postimg.cc/Gm416km0/Group.png",
    },
    {
        "id_ride": "2tn",
        "key": "tn4",
        "type":"Train",
        "fare": 15,
        "passenger":70,
        "image": "https://i.postimg.cc/Gm416km0/Group.png",
    },
    {   
        "id_ride": "3tn",
        "key": "tn4",
        "type":"Train",
        "fare": 15,
        "passenger":70,
        "image": "https://i.postimg.cc/Gm416km0/Group.png",
    }
    
]